twitter:
  api_key: OlsxhzeGzSaDvRPTDQcAFw
  callback_url: 'http://www.spot-app.com'
  consumer_key: OlsxhzeGzSaDvRPTDQcAFw
  consumer_secret: FHjKXmwGNoGWSuxiu5wR348NW4OQSLohAU3nEsfBsDo
  oauth_token_secret: FHqb2ppxVUf9KbshZAE3IEyHTCNX184oe6Rf89ltjo
  site: "http://www.spot-app.com"
  accounts:
    spotteam:
      oauth_token: 242458950-BEqB9qLKzkbjQUJx0LqTZPlBJcwxwIEVfIZT2azs
      oauth_token_secret: FHqb2ppxVUf9KbshZAE3IEyHTCNX184oe6Rf89ltjo
    wishlistitems:
      oauth_token: 257139696-fn1KXd8ikWziUwKYZjw4js7wMYrQz066gXFXPXEb
      oauth_token_secret: GCJpbjimjITZZWQZ2P1XohTb3gNRFvm0aHBAXmOZrLo
