wrapr:
  foursquare:
    client_id: TOCKXBSTM33KOK20MRTPEHGOJKQ0VKLKTTEOJJQC0JNEDSPZ
    client_secret: YQTCD0RUPXGERXQNA2MRAVIKHOQETGZB5NSG5YZKDYC5TR4E
  gowalla:
    api_key: 9a909f0e73a54520a37c45a0021fa345
    secret_key: a8123f0b28a64f5da58699cbd2f2f6fd
  flickr: 
    api_key: 2964c543386d6fa7ecb750744b20b236 
    api_secret: 8d5b8cd2c954c1de
  tumblr:
    email: "tumblr@placepopinc.com"
    password: "happy00ga"
    account: "spotteam"
    page_size: 20
    authors:
      - julia
      - jesse
      - niels
      - kent
      - jim
  fb_graph:
    client_id: 146911415372759
    client_secret: 1853a8a3fec8971ecedc41eaa75f5e91
    oauth_token: 146911415372759|uNNvv7XcknlF8PHj-vEwmt56HlA
  yelp:
    ywsid: e0LHa1Mbeo1jH34mU7wNug
    consumer_key: VqupBjbVhaMVITpHUm9Z4g
    consumer_secret: IYghP7tJz0YZUsc0qeGuE32Z8Ak
    oauth_token: mLKaxYyTsJSucqw0YXvh65Z6QNtv07KX
    oauth_token_secret: sHwZrwUQIgXcG6_7Lb5Qkmv8eoI