package_assets: on
embed_assets: off
javascript_compressor: closure

javascripts:
  vendor:
    - public/javascripts/vendor/jquery-1.4.4.min.js
    - public/javascripts/vendor/jquery-ui-1.8.11.custom.min.js
    - public/javascripts/vendor/jquery.tmpl.js
    - public/javascripts/vendor/logger.js
    - public/javascripts/vendor/jquery.validate.js
    - public/javascripts/vendor/jquery.jswipe.js
  scripts:
    - public/javascripts/shared/date_extensions.js
    - public/javascripts/shared/extensions.js
    - public/javascripts/shared/spot.js
    - public/javascripts/shared/behaviors.js
    - public/javascripts/shared/navigator.js
    - public/javascripts/shared/konami.js
    - public/javascripts/shared/gmap.js
    - public/javascripts/shared/app_preview.js
    - public/javascripts/shared/place_form.js
    - public/javascripts/shared/popover.js
    - public/javascripts/shared/jstooltip.js
    - public/javascripts/shared/search_emulator.js
    - public/javascripts/shared/lightbox.js
    - public/javascripts/shared/image_selector.js
    - public/javascripts/shared/slideshow.js
    - public/javascripts/shared/payment_dialog.js
    - public/javascripts/shared/views.js
    - public/javascripts/site/site.js
    - public/javascripts/admin/admin.js
    - public/javascripts/biz/promotion_calendar.js
    - public/javascripts/biz/biz.js

stylesheets:
  site:
    - public/stylesheets/site.css
  iphonesite:
    - public/stylesheets/iphonesite.css
  admin:
    - public/stylesheets/admin.css
  biz:
    - public/stylesheets/biz.css