development:
  adapter: mysql2
  database: spot_development
  username: root
  encoding: utf8
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: spot_test
  username: root
  encoding: utf8
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  host: masterdb.ec2
  encoding: utf8
  port: 3306
  database: spot_production
  username: spot
  password: p1rat3pantz
  pool: 5
  timeout: 5000

staging:
  adapter: mysql2
  database: spot_staging
  username: spot
  password: 5toP1tN0W
  encoding: utf8
  pool: 5
  timeout: 5000
  