common: &common
  morphology: stem_en
  charset_type: utf-8
  
development:
  <<: *common
  port: 9313
  
production:
  <<: *common
  port: 1182
  config_file: "/etc/searchd/searchd.conf"
  searchd_log_file: "/u/app/current/log/searchd.log"
  query_log_file: "/u/app/current/log/query.log"
  pid_file: "/u/app/shared/pids/searchd.pid"
  remote_sphinx: true
  address: "sphinx1.ec2"
  bin_path: "/usr/local/sphinx/bin"
  version: "0.9.9"

test:
  <<: *common
  port: 9313